### ISSUE TITLE
CONTRIBUTING.md commit style convention link broken

### ISSUE THREAD

**Issue by Tapppi** [gtramontina/ghooks#106]
The link to the angular style conventions in [CONTRIBUTING.md](https://github.com/gtramontina/ghooks/blob/master/CONTRIBUTING.md#semantic-release) returns 404.

Alternatives:  
* Angular's [*contributing.md*, section *git commit guidelines* ](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#-git-commit-guidelines)  
* Angular's [google doc on the subject](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y)

**Comment by kentcdodds** [comment]
Fixed it. Thanks for reporting!
