### ISSUE TITLE
opt-cli should be a devDependency

### ISSUE THREAD

**Issue by kentcdodds** [gtramontina/ghooks#125]
Unless I'm mistaken... But I think we should move `opt-cli` to a `devDependecy`. No reason to install it on other people's machines I think.

**Comment by ta2edchimp** [comment]
Users are currently able to opt-out of ghooks' install routine (doesn't make much sense to me now, idk if it did ever ¯\_(ツ)_/¯). This should than be removed.

**Comment by ta2edchimp** [comment]
[`bin/module-install`](https://github.com/gtramontina/ghooks/blob/master/bin/module-install#L4) is invoked as `npm install` script and atm depending on `opt-cli`.

**Comment by kentcdodds** [comment]
Oh, that's right! Ok, sounds good. Thanks!
