### ISSUE TITLE
More hooks...

### ISSUE THREAD

**Issue by joezimjs** [gtramontina/ghooks#13]
I was just curious why there aren't more hooks available for this? I don't currently have any particular reason for any specific additional hooks, but it just seems odd that you limited the set. For example, why not post-commit?

**Comment by gtramontina** [comment]
No specific reason… When I wrote this module, I got all the default `.sample` hooks that git provided and used them as a starting point. Adding new hooks is very straight forward (check this PR out https://github.com/gtramontina/ghooks/pull/12), and I'd welcome new additions :wink: :+1:

**Comment by gtramontina** [comment]
I'm closing this one. I've just added [![Join the chat at https://gitter.im/gtramontina/ghooks](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/gtramontina/ghooks?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) so we can have these questions answered there.
