### ISSUE TITLE
JIRA code validation commit hook

### ISSUE THREAD

**Issue by danieljoppi** [gtramontina/ghooks#138]
Does anyone have a git commit hook I can use that will ensure a JIRA issue number appears in the checkin message?

**Comment by kentcdodds** [comment]
Hi @danieljoppi,
Thanks for your interest in the project. This is more of a general question and not really about ghooks. I recommend you direct questions like this to StackOverflow in the future.

That said, you might check out [commitizen](https://github.com/commitizen/cz-cli) and the [cz-jira-smart-commit](https://www.npmjs.com/package/cz-jira-smart-commit) adapter. Not really a git hook, but it might help you out with what you're doing :)

Good luck!

**Comment by danieljoppi** [comment]
great!
