### ISSUE TITLE
Do not commit when pre-commit hook fails

### ISSUE THREAD

**Issue by trevordmiller** [gtramontina/ghooks#17]
I have installed `ghooks` and setup the config in my `package.json` like so:

```
...
 "config": {
    "ghooks": {
      "pre-commit": "gulp",
      "post-merge": "npm install"
    }
  },
...
```

The `gulp` task contains unit tests and linting; when someone commit's, `gulp` now runs - but the commit still works even if the `gulp` task outputs errors. I would like to setup the repo so that a user cannot commit until the `gulp` task (unit tests, linting etc.) passes without any errors; is there a parameter I can pass to do this or something? I don't see any information in the documentation...

**Comment by trevordmiller** [comment]
I just switched to [pre-commit](https://www.npmjs.com/package/pre-commit) and it works as I would expect:
![screen shot 2015-04-25 at 9 45 32 pm](https://cloud.githubusercontent.com/assets/5497885/7335795/8dff12c2-eb94-11e4-8159-13626741f711.png)

Guess I'll just use that. It would be nice if `ghooks` did something similar.

**Comment by gtramontina** [comment]
This is odd… `ghooks` exits with the same exit code as the command executed (https://github.com/gtramontina/ghooks/blob/master/lib/runner.js#L6).

Can you please double check what's the exit code of your command? You can run `echo $?` after running your `gulp` task.

**Comment by gtramontina** [comment]
@trevordmiller any updates on running `echo $?` after `gulp`?

**Comment by trevordmiller** [comment]
@gtramontina Not sure. I switched to [pre-commit](https://www.npmjs.com/package/pre-commit) and it worked as expected so I haven't taken any more time to debug ghooks.
