### ISSUE TITLE
Tower Git Client compatability

### ISSUE THREAD

**Issue by JamieMason** [gtramontina/ghooks#18]
Hi @gtramontina,
Thanks so much for creating ghooks, our team use it every day and find it really useful. 

There's one small issue though regarding support for GUI Git Clients such as [Tower](http://www.git-tower.com/);

![ghooks-tower](https://cloud.githubusercontent.com/assets/320492/7408272/06a24fc4-ef13-11e4-9dbb-e9fbd6afb9e6.png)

Searching for a fix, it looks like similar projects have also had [this problem](https://github.com/wecodemore/grunt-githooks/issues/8).

(I don't think this is environment related, but some output if needed)

    $ /usr/bin/env node --version
    v0.12.0

    $ which node
    /usr/local/bin/node

    $ echo $PATH
    /Users/jmason/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin

I hope this is useful, thanks.

**Comment by gtramontina** [comment]
Hey there @JamieMason. Thanks for reporting this and the detailed info! :+1:
Have you experienced this same issue with other GUIs? Can you please try to fiddle a little bit with the hooks under `.git/hooks` (as suggested here: https://github.com/wecodemore/grunt-githooks/issues/8#issuecomment-26218711) and see how far you get?

Let me know!

**Comment by JamieMason** [comment]
The problem seems to be that Tower (and other GUIs from what I've read) use a different `$PATH`

    /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core
    :/Applications/Xcode.app/Contents/Developer/usr/bin
    :/opt/homebrew-cask/Caskroom/tower/latest/Tower.app/Contents/Resources/git-flow
    :/usr/bin
    :/bin
    :/usr/sbin
    :/sbin

Incase it helps anyone (rather than throwing it away) the following workaround of executing `sh` instead of `node` and adding `/usr/local/bin` to the `$PATH` before executing `node` inline will work on Mac.

```shell
#!/usr/bin/env sh
# Generated by ghooks. Do not edit this file.
PATH="$PATH:/usr/local/bin"
__dirname=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
__filename="${0##*/}"

ghooks_runner="
var path = require('path');
var dirname = '$__dirname';
var filename = path.resolve(dirname, '$__filename');

try {
    require('ghooks')(dirname, filename);
} catch (e) {
    console.warn([
        'ghooks not found!',
        'Make sure you have it installed in node_modules.',
        'Skipping git hooks.'
    ].join('\n'));
}
"

node -e "$ghooks_runner"
```

Closing as in hindsight I think this is probably really an issue for @gittower.

**Comment by gtramontina** [comment]
Wow! :-)
Thanks a lot for the deep dive.
I'll add a note to README pointing here.

**Comment by bjrmatos** [comment]
i'm a little confused.. how i can apply this workaround? do i need to modify all the hooks everytime i clone my project on a new machine?

**Comment by bjrmatos** [comment]
@JamieMason i'm a little confused.. how i can apply this workaround? do i need to modify all the hooks everytime i clone my project on a new machine?

**Comment by JamieMason** [comment]
@bjrmatos it's something that @gtramontina (or a contributor) would need to apply to ghooks itself so that it works with these GUI apps — more work is needed though to test and finish it before it could be used.

**Comment by gittower** [comment]
When you run Git from the command line, it runs in the environment as set up by your Shell. GUI OS X apps, however, have no knowledge about your shell - and the PATH environment can be changed in many different places.

See Tower's online docs for more info on how to deal with this: http://git-tower.com/help/mac/faq-and-tips/faq/hook-scripts

**Comment by kentcdodds** [comment]
I have to start SourceTree from the command line to get it to load my path properly.

**Comment by gajus** [comment]
For the record, the simpler way to work around this (assuming your git hooks depend on environment variables set by the shell), is to simple start Git Tower from the CLI, e.g.

```bash
gittower ./any-repository
```

This will open Git Tower client aware of the environment variables set by the shell script.

**Comment by gajus** [comment]
I find it a bit odd though that Tower GUI simply cannot source `./bashrc` upon. I'd imagine that there are quite a few developers that use `./bashrc` (or equivalent) to setup their working environment, e.g. `nvm use node`.

**Comment by JamieMason** [comment]
Nice find @gajus, thanks.

**Comment by kentcdodds** [comment]
We may actually make progress on #40. Subscribe to that issue to keep updated 👍

**Comment by ashblue** [comment]
@gajus Solution magically fixed some weird behavior on OSX High Sierra.
