### ISSUE TITLE
git svn dcommit hook

### ISSUE THREAD

**Issue by dmaslov** [gtramontina/ghooks#19]
Hi!
Is it possible to add hook for ```git svn dcommit``` command? 
It would be great!

**Comment by gtramontina** [comment]
I've dealt with git-svn about 5 years ago, but not extensively... does it support (or integrates with) git hooks? Like the ones under the `.git/hooks` directory?

**Comment by noamokman** [comment]
@dmaslov is this still relevant? or can we close this issue?

**Comment by dmaslov** [comment]
@noamokman sorry, not relevant!
