### ISSUE TITLE
Accept array of files in package.json's config?

### ISSUE THREAD

**Issue by adelgado** [gtramontina/ghooks#25]
I think it could be useful to have a list of actions that could be ran on a specific hook. For example, I could have a config section in the following format:
```json
  "config": {
    "ghooks": {
       "post-merge": ["hooks/check-file-changes.sh", "hooks/verify-asset-checksum.sh", "hooks/whatever.sh"],
       "post-rewrite": ["foo.js", "bar.lua"]
```
and it would call the respective files listed in the array, in order.

Do y'all think that would be useful?

**Comment by gtramontina** [comment]
Hi there! Thanks for your suggestion :beers:!
Git itself doesn't support multiple hooks of the same type, so I'd prefer to keep it consistent. Here's a couple of suggestions on how to run multiple commands with the current setup:

* Using the logical `&&`:
```json
{ …
"post-merge": "hooks/check-file-changes.sh && hooks/verify-asset-checksum.sh && hooks/whatever.sh"
… }
```
* Using a utility like `make`:
```json
{ …
"post-merge": "make post.merge"
… }
```
I, personally, prefer the latter. :smile: 

That said, I'm all ears… if we get enough :+1:, I'd gladly merge a PR.

**Comment by noamokman** [comment]
Hi there @adelgado!
I agree with @gtramontina, logical `&&` is the better option.
This is what developers use to achieve the same result for npm scripts.
Personally, I use [gulp](https://github.com/gulpjs/gulp) to handle tasks.

**Comment by adelgado** [comment]
@noamokman It's really a matter of opinion, there isn't a "better" option. I prefer to have the files listed explicitly in an array because I think it's more semantic. Also, I don't need to rely on the underlying shell's interpretation of `&&`, which may not pose an issue, but it's a preference of mine. Thirdly, it allows me to format hooks with a single one per line, which make diffs when adding or removing hooks clearer.

But that's the beauty of open source, I have [my own fork of this repo](https://github.com/adelgado/ghooks), and there I can do it the way I think is best :-) In the end, I guess I don't mind that much, given that's not one of the changes I integrated there.

**Comment by kilianc** [comment]
@adelgado I have the same issue, take a pick a at #34 would that suit your use case?

**Comment by kentcdodds** [comment]
@adelgado, I would recommend that you have a single shell script that calls out to the other scripts you want or just use `&&` as previously recommended. All the best!
