### ISSUE TITLE
Add node_modules/.bin to $PATH

### ISSUE THREAD

**Issue by kentcdodds** [gtramontina/ghooks#26]
Just like [npm-scripts](https://docs.npmjs.com/cli/run-script) do:

> In addition to the shell's pre-existing PATH, npm run adds node_modules/.bin to the PATH provided to scripts. Any binaries provided by locally-installed dependencies can be used without the node_modules/.bin prefix. For example, if there is a devDependency on tap in your package, you should write:
> 
> "scripts": {"test": "tap test/\*.js"}
> instead of "scripts": {"test": "node_modules/.bin/tap test/\*.js"} to run your tests.

This would be very handy!

**Comment by kentcdodds** [comment]
I'm investigating now. [Here](https://github.com/npm/npm/blob/master/lib/run-script.js) is where the scripts are run, and [here](https://github.com/npm/npm/blob/master/lib/utils/lifecycle.js) is where PATH gets added. Would love it if we could get the path adding stuff open sourced, or find an open source solution...

**Comment by gtramontina** [comment]
Yes!! I thought about this in the very beginning of the project and for whatever reason I forgot about it... I've done something like that here: https://github.com/gtramontina/npmw :grin: -- more specifically at https://github.com/gtramontina/npmw/blob/master/lib/npmw.template#L15-L16

I believe this should be quite straight forward.

**Comment by kentcdodds** [comment]
I think it'd be cool if we could take some of what `npm` has [here](https://github.com/npm/npm/blob/master/lib/utils/lifecycle.js#L16-L24) and [here](https://github.com/npm/npm/blob/master/lib/utils/lifecycle.js#L79-L94) and open source it, then `ghooks` can use it... I'll let you know when I've got that done. 😀

**Comment by kentcdodds** [comment]
Done! http://npm.im/add-to-path

**Comment by bjrmatos** [comment]
I think this would be useful for better git's GUI integration #18 :D

**Comment by kentcdodds** [comment]
I don't think so actually. The problem is that git GUIs don't even load `node` in the first place :-(

**Comment by noamokman** [comment]
:+1: this repo seems a bit in active.. need some help?

**Comment by kentcdodds** [comment]
Would totally love some help :-) FYI, add-to-path was renamed and altered a bit to become [manage-path](http://npm.im/manage-path)

**Comment by noamokman** [comment]
Yeah just followed up on your second PR for npm.
Hope you manage to squeeze it in :smile:
I wanna close all PRs and issues. I can make a PR for this issue but I wanna clean up a bit first.
What do you say?

**Comment by kentcdodds** [comment]
That sounds awesome! I'll keep an eye on things :-)
