### ISSUE TITLE
Check for scripts to run in the npm `scripts`

### ISSUE THREAD

**Issue by kentcdodds** [gtramontina/ghooks#27]
What do you think of this? Given:

```javascript
{
  "scripts": {
    "pre-commit": "eslint src/"
  }
}
```

ghooks would run:

```
npm run pre-commit
```

This would make #26 unnecessary for my personal use case (though still handy probably).

The one thing that I can't quite figure out is how to still support #23 with this... In the case of #23, I would expect the arguments to still get forwarded on:

```javascript
{
  "scripts": {
    "commit-msg": "validate-commit-msg $1"
  }
}
```

ghooks would run:

```
??? how does it forward on the arguments
```

So, for cases where the arguments are needed, you'd probably still have to use the `ghooks` in `config`....

After having written this, I'm questioning whether it'd be worth it. Thoughts?

**Comment by noamokman** [comment]
I think we should close this one, and focus on #26.
This sort of behavior is confusing to users and I think that different options for ghooks is the way to go.
Also, with #24 merged, its irrelevant :sweat_smile:

**Comment by kentcdodds** [comment]
Agreed. I'm actually almost finished with #26 :-)
