### ISSUE TITLE
`#!/usr/bin/env node` no longer working on El Capitan

### ISSUE THREAD

**Issue by remie** [gtramontina/ghooks#30]
With the new System Integrity Protection scheme of El Capitan (http://apple.stackexchange.com/a/193379), the common workaround for getting `#!/usr/bin/env node` to work on OSX is no longer valid. Although this is technically not an issue of ghooks, it does render the module useless. Any thoughts?

**Comment by kentcdodds** [comment]
Hmm... I'm not sure why it's not working for you because it's been working for me seamlessly since I upgraded to El Capitan a month ago...

**Comment by remie** [comment]
@kentcdodds, ok so I guess I should have provided a bit more information on this subject as it is a problem with many layers.

The `#!/usr/bin/env node` approach works if node is in the path. The normal workaround for fixing this is to create a symlink from `/usr/local/bin/node` to `/usr/bin/node`. This would automatically place `node` on the global PATH environment variable.

Now with El Capitan, the `/usr/bin` folder is no longer writable. So the symlink approach is no longer viable. Within the user scope, this can be fixed by simply adding `/usr/local/bin` to the PATH in your `.bash_profile` file. However, this only fixes the problem for terminal / bash-based usage.

Unfortunately, when starting applications in OSX, the `.bash_profile` file is not taken into consideration and a very limited PATH environment variable is passed to the application. This causes issues with the `#!/usr/bin/env node` solution in ghooks when using a git GUI like Sourcetree. For this scenario there is another workaround: http://stackoverflow.com/a/26586170

I guess you either already had the symlink in place when upgrading to El Capitan, or are not using a GUI for your git operations. In my case, I did a clean install of El Capitan and am using Sourcetree. 

Either way, fortunately there is a workaround for this problem so i guess there is nothing to fix. I will be closing the issue. Thanks for looking into this!

**Comment by kentcdodds** [comment]
Oh! You know what, you're totally right. I should probably add something to the README about this. This is really frustrating that the PATH isn't set correctly for apps started using the normal method. To get around this I created an alias and I start SourceTree with it in the command line:

```
st="open /Applications/SourceTree.app/Contents/MacOS/SourceTree"
```

That's worked great for me! Thanks for bringing this up and for your patience!

**Comment by kentcdodds** [comment]
Heh, looks like this is already in [the README](https://github.com/gtramontina/ghooks#common-issues) :-) came from #18
