### ISSUE TITLE
add support for .ghooksrc since touching package.json is a little bit too opinionated.

### ISSUE THREAD

**Issue by kilianc** [gtramontina/ghooks#33]
`package.json` get's published to npm and other registries, other than being a really intimate place for most projects. There should be an option to read `.ghooksrc` first.

For example I don't even have a `config` section in my `package.json`.

**Comment by kilianc** [comment]
this would become obsolete if #34 lands.

**Comment by kentcdodds** [comment]
As noted in #34, we're not going to do this. The [`config`](https://docs.npmjs.com/files/package.json#config) section is the official place to put stuff like this. Thanks!
