### ISSUE TITLE
use plain bash instead of node because is too env dependent.

### ISSUE THREAD

**Issue by kilianc** [gtramontina/ghooks#34]
This is how I would love it to work:

* On install create `.ghooks` or `hooks` folder or similar on project root
* Have a plain bash file `if [ -e "../../ghooks/$hookname" ]` as hook in `.git/hooks`

This way we remove the need of any configurations file, we can use whatever language we want, we can have developer specific `.env` files to fix `gittower` alike GUI problems and all hooks are explicitly versioned and only in one place.

Also we could probably use `symlinks` in `.git/hooks` since it's the same file over and over.

**Comment by kilianc** [comment]
Before forking I would love to understand if a PR is welcome, the way this works right now is not viable for my team. From the PM to the designer we all use git, and where everyone's node binary is unpredictable. Also most checks are better written in `bash` than node.

**Comment by kilianc** [comment]
I got a prototype running with few lines

Every file in `.git/hooks` is a symlink to this, in this instance I symlinked `.git/hooks/pre-commit`
```bash
#!/bin/bash

FILENAME="$(basename "$0")"
HOOK_PATH="$(pwd)/hooks/$FILENAME"

echo "> checking for ./hooks/$FILENAME existence"

if [ -f "$HOOK_PATH" ]; then
  echo "> ./hooks/$FILENAME exists, running"
  echo ""
  $HOOK_PATH
fi
```

Then I have this in `hooks/pre-commit`
```bash
#!/bin/bash

# project specific check
if [ -f ./hooks/.env ]; then
  ./hooks/.env
else
  echo "> please create hooks/.env file"
  exit 1
fi

# project specific commands
node -v
echo "this is a test"
```

And `hooks/.env` is a git ignored file containing

```bash
. ~/.nvm/nvm.sh
```

**Comment by kentcdodds** [comment]
I appreciate what you're trying to do and I think that it looks pretty neat. However I don't think that we're going to do anything like that for this project. We can assume the node environment because ghooks is distributed via npm. Also, it's quite easy to call a bash script from the package.json configuration and I do it all the time.

I would prefer to not make such a significant change to how this library works. So I recommend that you either fork this repo or create your own solution. Good luck!

**Comment by kilianc** [comment]
@kentcdodds thanks for the reply. I will go ahead and hack something together :D 

Just a note:

> We can assume the node environment because ghooks is distributed via npm.

This is an unsafe assumption. If I do `/my/custom/thing/npm install` or I git commit through a different shell from what I used to install the project it won't work because the entry point is node. This is the case for git GUI like Tower and similar.

This said, I understand it is outside the scope of this module to fix this use case and I will go my own way :)

**Comment by tracker1** [comment]
@kilianc of I `npm install -g ghooks` in windows, I do have node, I don't have bash... If you're using a custom npm client that doesn't use node, back for you.

As an aside, I do have and use Nash in windows... That said, there's more to node than just a Linux environment with bash, and this is an npm/node module...

**Comment by tracker1** [comment]
Last comment from phone, forgive the spelling/grammar issues

**Comment by kilianc** [comment]
@tracker1 not sure what you are referring to with this

> @kilianc of I npm install -g ghooks in windows, I do have node, I don't have bash... If you're using a custom npm client that doesn't use node, back for you.

You missed my point about custom `PATH` with custom node installs if you use multiple versions of node on the same machine.

> As an aside, I do have and use Nash in windows... That said, there's more to node than just a Linux environment with bash, and this is an npm/node module...

I see no issues supporting bat files or whatever format windows git hooks are written into.

>  this is an npm/node module

Kind of irrelevant if it doesn't actually allow me to use node with `nvm`. It's a tool for node and npm projects, being blindfolded and using node regardless even if it is obviously a road block is kinda silly.

**Comment by kilianc** [comment]
turns out what I want is already out there: https://github.com/tarmolov/git-hooks-js

**Comment by kilianc** [comment]
I am just gonna drop it here, I hacked together my own implementation https://github.com/kilianc/shared-git-hooks which is pretty much like husky but without configuration.

Main differences are:

* entry point is a bash script
* $PATH is frozen at the same value it was when installed
* all scripts in .git/hooks are symlinks

**Comment by kentcdodds** [comment]
Cool. Tweeted. :+1:

**Comment by timdp** [comment]
@kilianc Thanks, husky works great!

I was trying to use ghooks inside [babun](http://babun.github.io/) and ran into path translation issues, where somewhere along the line, `/c/src/repo/git/hooks` was getting turned into `C:\cygdrive\c\src\repo\.git\hooks`, causing breakage:

```bash
➜  repo git:(master) git checkout experimental
Switched to branch 'experimental'
Your branch is up-to-date with 'origin/experimental'.
module.js:341
    throw err;
    ^

Error: Cannot find module 'C:\cygdrive\c\src\repo\.git\hooks\post-checkout'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:141:18)
    at node.js:933
```

Husky doesn't suffer from this issue. I'm not claiming the error is on ghook's part, but it'd still be nice if whatever husky is doing to make it work with babun could somehow trickle into ghooks. (Yes, I'm fully aware that Cygwin is a total pain.)
