### ISSUE TITLE
Using git `--work-tree` option blows up with ghooks

### ISSUE THREAD

**Issue by keithamus** [gtramontina/ghooks#35]
I know this is a weird issue, but I've just encountered that using `--work-tree` (as in `git --work-tree some/folder commit`) causes ghooks to blow up with the following:

```js
$ git --work-tree ./foo commit -m 'an example of --work-tree crashing'
module.js:339
    throw err;
    ^

Error: Cannot find module '<snip>/ghooks-test/foo/package'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at commandFor (<snip>/ghooks-test/node_modules/ghooks/lib/runner.js:17:13)
    at run (<snip>/ghooks-test/node_modules/ghooks/lib/runner.js:8:17)
    at <snip>/ghooks-test/.git/hooks/pre-commit:7:20
    at Object.<anonymous> (<snip>/ghooks-test/.git/hooks/pre-commit:8:3)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
```

I think it's a case of simply try/catching and just cracefully failing if the package.json cannot be found. I'm happy to work on a PR if you're happy to accept one? 

FYI if you're thinking "what in the world are you using --work-tree for?!" - well, I'm trying to have a gh-pages branch which tracks my `site` directory (rather than repo root) - using https://github.com/lukekarrys/git-directory-deploy

**Comment by kentcdodds** [comment]
Makes sense. (TIL: `--working-tree`). I would prefer to actually improve ghook's detection of a package.json. I'm happy to accept a pull request, but I would love it if you could actually make it work for your case rather than just fail softly. :smile:

**Comment by keithamus** [comment]
@kentcdodds what kind of behaviour would you expect from ghooks package.json? It could look up the tree until it hits a package.json, and then assume that is the project folder - does this sound ok?

**Comment by kentcdodds** [comment]
I think it should look up the tree until it finds a `package.json` or a `.git`. What do you think?

**Comment by keithamus** [comment]
I agree. Which first though? I suppose it depends on both, so it should just search up the tree for both independently?

**Comment by keithamus** [comment]
Also, what happens if it doesn't find one? Do we fail hard or gracefully?

**Comment by kentcdodds** [comment]
Why don't we fail hard. If it's a problem, people can use `--no-verify`

**Comment by keithamus** [comment]
The problem with `--no-verify` is that while `pre-commit` and `commit-msg` hooks are ignored, `prepare-commit-msg` is not - and so even with `--no-verify`, failing hard means users still cannot commit. To demonstrate:

```js
$ git --work-tree ./foo commit -m 'an example of --work-tree crashing'
module.js:339
    throw err;
    ^

Error: Cannot find module '<snip>/ghooks-test/foo/package'
...
    at <snip>/ghooks-test/.git/hooks/pre-commit:7:20 <---- NOTE: pre-commit
...

$ git --work-tree ./foo commit -m 'an example of --work-tree crashing' --no-verify
module.js:339
    throw err;
    ^

Error: Cannot find module '<snip>/ghooks-test/foo/package'
...
    at <snip>/ghooks-test/.git/hooks/prepare-commit-msg:7:20 <---- NOTE: prepare-commit-msg
...
```

We could, I suppose, hard fail on some, while soft fail on others? `prepare-commit-msg` soft failing isn't the end of the world, because you just end up with an empty commit message (but hard failing means you can't commit).

**Comment by kentcdodds** [comment]
I see what you mean. Why don't we just warn and fail soft.

**Comment by keithamus** [comment]
Cool, I'll get to work on a PR tomorrow.

**Comment by kentcdodds** [comment]
Great. Thanks! :D

**Comment by keithamus** [comment]
Looks like the proposed implementation would probably fix #3 and #28 btw.

**Comment by kentcdodds** [comment]
:tada:

**Comment by gtramontina** [comment]
Aw crap.. :stuck_out_tongue:
I've got some free time and though about contributing a little more to ghooks (so you don't think I've abandoned it lol). I've just submitted a PR to address #3... Hopefully this does not get in your way, @keithamus ... If it does, just ignore it! :+1: 

Thanks you all!!

**Comment by gtramontina** [comment]
Btw, would allowing a config like `root: "./my-dir"` in the `package.json` help in any way?

**Comment by kentcdodds** [comment]
I like that idea a lot, that would address #28 I think :D
