### ISSUE TITLE
Better linting

### ISSUE THREAD

**Issue by gtramontina** [gtramontina/ghooks#42]
There are a few `jshint` entries related to code style that are getting deprecated and it is suggested the use of [`jscs`](http://jscs.info/).

We could take this opportunity to revisit tooling and styles/preferences or we could simply go with presets like [eslint](http://eslint.org/) + [a preset](https://www.npmjs.com/search?q=eslint-config), or even [xo](https://github.com/sindresorhus/xo) or [standardjs](http://standardjs.com/).

:thought_balloon:?

**Comment by kentcdodds** [comment]
I'm a big fan of eslint. I have my own preset: https://www.npmjs.com/package/eslint-config-kentcdodds but I'd be good with standard or xo.

**Comment by gtramontina** [comment]
Neat! I'll check it out!

**Comment by kentcdodds** [comment]
You might be interested in the `--fix` flag. Also.... It's kind of unorthodox, but http://kcd.im/semicolons

**Comment by gtramontina** [comment]
I've used that flag and I love it! :-D

Re: semicolons, I don't really have a strong preference as long as the reasons you posted on your `Conclusion` are clear! :smile: 

For anyone getting started with javascript, I'd say using semicolons are a rule until you know it well enough and understand why you can get rid of them. A similar advice I'd give on the SOLID principles to anyone getting started with OO. I'd say follow them as rules until you know them well enough to recognize when to break them. :+1:

**Comment by kentcdodds** [comment]
The challenge is there are so many rules around where to use semicolons. It's easier just to tell the newcomer: don't use them

**Comment by gtramontina** [comment]
If they "don’t transpile/uglify and lint", which can be pretty common when learning, they can run into the infamous `return` issue and learn about ASI the hard way!  `¯\_(ツ)_/¯ `

Anyway, I'm liking your defaults on https://www.npmjs.com/package/eslint-config-kentcdodds … I'll get it in soon. Going to :sleeping: now. Cheers!
