### ISSUE TITLE
pre-push only for master

### ISSUE THREAD

**Issue by sebastienbarre** [gtramontina/ghooks#44]
Hi. I was wondering if you would know of a way to configure `ghooks` to only trigger the `pre-push` action for a specific branch, specifically `master`.
My use case is the following: 
```
   "ghooks": {
      "pre-push": "npm run coverage && npm run coverage:check"
    },
```
In this scenario, I use `pre-push` to stop anybody (mostly myself) from pushing when the code coverage is below a specific threshold. However, I'd like to restrict this safety check to `master` only -- it is OK to push to a work-in-progress branch, even when the coverage is low (assuming that it will get better by the time it's ready to merge it with `master`).

Thanks!

**Comment by kentcdodds** [comment]
Hi @sebastienbarre! Thanks for your interest in the project. I totally understand where you're coming from and what you say makes sense. However, I want to avoid conflating this project with too much knowledge of the outside world (like what branch you're on). I'd rather keep this as simple and lego-like as possible. You could definitely accomplish this with another script (and even [open source it](http://kcd.im/write-oss)).

```
"ghooks": {
  "pre-push": "./scripts/on-master && npm run coverage && npm run coverage:check"
}
```

Where `on-master` could run `git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,'` to determine whether you're on the master branch, and `exit 1` if you aren't (which would prevent downstream commands from running.

Thanks again. Good luck!

**Comment by gtramontina** [comment]
Yeah. This would be up to your hook to do. You can also add the `--short` flag and avoid `sed`ing: `git symbolic-ref --short HEAD`.

I believe that something like the following would do it (not tested):
```
"ghooks": {
  "pre-push": "([ "master" != `git symbolic-ref --short HEAD` ] && true) || (npm run coverage && npm run coverage:check)"
}
```
But at this point it is already a little hard to read, so you could just break things down into more focused scripts as @kentcdodds suggested.

**Comment by sebastienbarre** [comment]
Perfect, that's all I needed guys, a push in the right direction. Thanks, and keep up the good work.
