### ISSUE TITLE
GitBash for Windows has issues with hooks in .git folder

### ISSUE THREAD

**Issue by Colonel-Meowzer** [gtramontina/ghooks#47]
Hello,

I am using the ghooks package as part of another package and noticed a small issue. When trying to run git commit, I was getting an error saying:

**"." is not recognized as an internal or external command, operable program or batch file.**

I was able to do everything but commit to this project. I was able to pin down the source to the runner.js. Since my hooks are located inside C:/.../.../ProjectDirectory/.git, windows was trying to execute this hook with a "." in the path and it was confusing it. I have a fix for it but wanted to open an issue.

**Comment by kentcdodds** [comment]
Not certain I understand the issue you're describing, but feel free to [makeapullrequest.com](http://makeapullrequest.com) and maybe that'll help me understand.

**Comment by Colonel-Meowzer** [comment]
Nevermind. This was an environment issue related to my project. I apologize for the inconvenience

**Comment by kentcdodds** [comment]
No worries! Glad you got it worked out!

**Comment by melihovv** [comment]
@Colonel-Meowzer I have the same issue too. Can you describe what was wrong?

**Comment by Colonel-Meowzer** [comment]
It has been a little bit but I want to say that it was an issue with the PATH variable. I think the node path was wrong as I had a task set up in package.json for commitizen that would end up executing this code. Let me know if that works.

**Comment by melihovv** [comment]
In my case the error was from package.json
```
  "config": {
    "ghooks": {
      "pre-commit": "./vendor/.bin/phpunit"
    }
  },
```
I replace it to this
```
  "config": {
    "ghooks": {
      "pre-commit": "phpunit"
    }
  },
```
and it works now
