### ISSUE TITLE
Add opt-in functionality

### ISSUE THREAD

**Issue by kentcdodds** [gtramontina/ghooks#48]
Allow the user to specify they'd like to only run the hooks if a certain file is present. This file is gitignored so you opt-in by creating the file (and maybe it should have contents, like which hooks to opt-into).

This would make it easier for beginners to start contributing by removing barriers until they're comfortable with the project and contributing regularly.

**Comment by gtramontina** [comment]
Let me see if I got this correctly… If a file, say `.ghooksignore`, exists, then skip running all (or the ones listed in the file) hooks.

I see from the referenced GH issue this is related to a contributor not being too familiar with git itself (`--no-verify`). So implementing this feature would remove barriers for contributing to projects that _use_ `ghooks`.

If what I understand is correct, I'm not sure if this should be `ghooks`' responsibility… Perhaps a new module or script that you'd prepend to your project's hooks? Something like:

```json
…
    "ghooks": {
      "precommit": "skiphook || make test",
      "prepush": "skiphook || make lint"
    }
…
```

:thought_balloon:?

**Comment by kentcdodds** [comment]
Ah, that's an interesting idea. Hmm... I think I like that. Maybe the module could be more generically named, but I like the idea.

For implementation, I was thinking that it'd be cool to have an opt-in and opt-out So then you could say `opted in precommit make test` and `opted out prepush make lint`

```js
"ghooks": {
  "precommit": "opt --in precommit --exec \"make test\"",
  "prepush": "opt --out prepush --exec \"make lint\"",
}
```

Then you'd have files:

**.opt-in**
```
precommit
```

**.opt-out**
```
prepush
```

The behavior would be that if it's an `opt --in` then you MUST have the string specified in the `.opt-in` file. If it's an `opt --out` then you MUST NOT have the string specified in the `.opt-out` file. Then the `--exec` would be what to execute in the scenario that it passes the test.

Thoughts?

**Comment by kentcdodds** [comment]
FWIW, https://www.npmjs.com/package/opt-cli is available :-)

**Comment by gtramontina** [comment]
Yeah, naming things is not one of my best skills. :smiley:
I like `opt`... And have a feeling you've already started sketching some code… :smile:

**Comment by kentcdodds** [comment]
Haha, in my brain only. I wont have time to work on this very soon I think so if you wanna do it be my guest! :D

**Comment by gtramontina** [comment]
Same here… Full plate.
I'll drop I line here if/when I start something so we don't step on each other's toes :+1:

**Comment by kentcdodds** [comment]
Same :+1:

**Comment by ta2edchimp** [comment]
I've shamelessly stolen your idea for an `opt-cli` module. Please, [have a look](https://github.com/ta2edchimp/opt-cli) and tell me what you think :smiley:

**Comment by kentcdodds** [comment]
Gave that every positive reaction available :D

**Comment by gtramontina** [comment]
Closed by https://github.com/gtramontina/ghooks/pull/51
