### ISSUE TITLE
ghooks not found when it is indeed installed

### ISSUE THREAD

**Issue by gaowhen** [gtramontina/ghooks#55]
I did everything according to the readme instruction, but still got the warning 'Make sure you have it installed on your "node_modules"'.

I also tried to require ghooks in the project path, and it seems like it is installed correctly.

    > var ghooks = require('ghooks')
    > ghooks
    [Function: run]

**Comment by kentcdodds** [comment]
Could you provide your node and npm versions please? :-)

**Comment by gaowhen** [comment]
I finally found the problem.The code installed from npm is different from the code in this repository.

For example, the install function in lib/install.js in the node_modules is 

    function install(hooksDir, hook) {
      var file = hookFile(hooksDir, hook);
      if (needsBackup(file)) { backup(file); }
      fs.writeFileSync(file, template.content);
      fs.chmodSync(file, '755');
    }

And according to the code above. It is indeed right to  write the warning message to the hook files. I can show you the whole source code if you want.

**Comment by gaowhen** [comment]
Oh, my fault. I misunderstood it. I used gulp-symlink before and I thought ghooks symlinks files to .git/hooks as the same.

Sorry for that.
