### ISSUE TITLE
Latest ghooks npm module fails to install on windows machines

### ISSUE THREAD

**Issue by dbaeumer** [gtramontina/ghooks#63]
![image](https://cloud.githubusercontent.com/assets/1931590/14140234/2090120a-f678-11e5-969c-632a416575d8.png)

**Comment by gtramontina** [comment]
Oh wow, that was a quick bite! Sorry about that… 
I'll look into moving the `[ ! -d "./dist" ]…` behavior to within the `install` script in a cross platform way.

**Comment by gtramontina** [comment]
Hey @dbaeumer, could you please git `ghooks@1.1.1` a try? We've just pushed a fix…

**Comment by kallaspriit** [comment]
Had the same issue, latest 1.1.1 works again for me :)

**Comment by dbaeumer** [comment]
@gtramontina 1.1.1 works again. Thanks for the quick fix.

**Comment by kentcdodds** [comment]
:tada:
