### ISSUE TITLE
Introduce a "canary" ("next") release channel

### ISSUE THREAD

**Issue by ta2edchimp** [gtramontina/ghooks#72]
Regarding current issues ( #70, #71 ), it may be worth thinking about introducing a `next` release channel.
I had a quick look into how `semantic-release` does their own publishing of versions:

They have three (publicly accessible) branches:

1. **`caribou`** is the one, all Pull Requests are compared to and merged into.
It has the `publishConfig` field, pointing to `"tag": "next"`.
Releases made from this branch are labelled `Pre-Release`.
2. **`badger`** is the one that the non-Pre releases are made from, its package.json has no `publishConfig` field, thus pointing to tag `latest`.
3. **`alpaca`** is the one I, at a first glance, do not have the slightest clue about what it does. Its `.travis.yml`'s deploy section seems full of an ancient dialect even my great-grandfathers did not speak anymore.

Maybe we can copy that behavior:

- making the current **`master`** our `caribou` (for `next` tagged pre-releases)
- create a new branch **`stable`** or sth like that to become our `badger` (for the `latest` tagged ready-for-production releases) to merge into from `master` regularly (to be defined).

What do you think?

**Comment by kentcdodds** [comment]
I've actually considered doing this to have more control over releases. We just occasionally create a PR from `master` to `stable` whenever we want to release. I think that's reasonable. :+1:

**Comment by ta2edchimp** [comment]
Hmm... When going with the idea of merging from `master` to `stable` to release in dist-channel `latest` we'd loose any connection between versions of the dist-channels, wouldn't we?
What I mean is: a `1.2.3 next` would not necessarily be identical to a `1.2.3 latest` eventually, but a `latest` release version `1.1.0` could instead include all changes from `1.0.x` that created more individual versions on `latest`, up to `1.2.3`.
You know what I mean?

But, tbh I don't think of this as a big problem...

**Comment by kentcdodds** [comment]
We could start the `latest` version at `900.0.0`. I have no problem doing that. It's just a number :-)

**Comment by ta2edchimp** [comment]
I rather thought of having an advantage when there's a direct relationship between versions of the same number from different dist-channels... Immediately after I posted the comment I came to the conclusion that would be completely irrelevant.

Right now I only have issues wrapping my head around arranging and configuring a tangible setup as described in the opening post.
Would you mind doing that some time around the weekend / beginning of the upcoming week? I might finish the WIP PR and some other things for `ghooks` in the upcoming days and would like to save us from another "exit-with-error"gate ( #70 ) :stuck_out_tongue_winking_eye:

**Comment by kentcdodds** [comment]
I'll see if I can find the time. But I'm afraid this project is currently lower on my list of priorities right now :-/

**Comment by ta2edchimp** [comment]
Np. Maybe I sort it out myself or @gtramontina does it :grin:, I _should_ understand it sooner or later either way :stuck_out_tongue_winking_eye:

**Comment by ta2edchimp** [comment]
Hmm... I spent all weekend to find an approach to somehow achieve what we want in a fully automated manner (that is, simply occasionally making a PR from `master` to a new branch `latest`) and failed at it :(

Atm I'm not able to find a way that would not require any manual work to accomplish this task (that is, at least altering the `release` and `publishConfig` fields in `package.json` on a branch to merge into).
But in a recent discussion over at the `semantic-release` repo, someone [posted a script he is using after a successful build](https://github.com/semantic-release/semantic-release/issues/207#issuecomment-202116485) that adds a dist-tag to the latest published version, based upon the branch it's performed from. Maybe something we can build upon.

**Comment by kentcdodds** [comment]
Honestly, the more I think about it, the more I think it's not necessary to come up with a big complicated release thing for this project. After a few major bug fixes and features are implemented I don't really see this project getting a lot of work on it. Hopefully we can find the end of this project eventually :-)

**Comment by ta2edchimp** [comment]
Ok, let's not overcomplicate things then ...

**Comment by gtramontina** [comment]
Sorry for the silence… Agree! :+1: :smile:
